// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAppDirectory() {
  return window['go']['main']['App']['AddAppDirectory']();
}

export function AddDirectory() {
  return window['go']['main']['App']['AddDirectory']();
}

export function AddFiles() {
  return window['go']['main']['App']['AddFiles']();
}

export function ClearFileList() {
  return window['go']['main']['App']['ClearFileList']();
}

export function FormatFileSize(arg1) {
  return window['go']['main']['App']['FormatFileSize'](arg1);
}

export function GetAppDirectory() {
  return window['go']['main']['App']['GetAppDirectory']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetFileList() {
  return window['go']['main']['App']['GetFileList']();
}

export function GetFileLogs(arg1) {
  return window['go']['main']['App']['GetFileLogs'](arg1);
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function IsProcessing() {
  return window['go']['main']['App']['IsProcessing']();
}

export function OpenFileLocation(arg1) {
  return window['go']['main']['App']['OpenFileLocation'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartConversion() {
  return window['go']['main']['App']['StartConversion']();
}

export function StopConversion() {
  return window['go']['main']['App']['StopConversion']();
}
