// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddAppDirectory():Promise<Array<string>>;

export function AddDirectory():Promise<Array<string>>;

export function AddFiles():Promise<Array<string>>;

export function ClearFileList():Promise<void>;

export function FormatFileSize(arg1:number):Promise<string>;

export function GetAppDirectory():Promise<string>;

export function GetConfig():Promise<models.AppConfig>;

export function GetFileList():Promise<Array<models.FileInfo>>;

export function GetFileLogs(arg1:number):Promise<Array<string>>;

export function GetLogs():Promise<Array<string>>;

export function IsProcessing():Promise<boolean>;

export function OpenFileLocation(arg1:string):Promise<void>;

export function SaveConfig(arg1:models.AppConfig):Promise<void>;

export function StartConversion():Promise<void>;

export function StopConversion():Promise<void>;
